import { LayoutOption } from './layout-option.model';

export interface GenerateLayoutResponse {
  /**
   * AI generated summary of the page.
   */
  page_summary: string;

  /**
   * Recommended layout identifier.
   */
  recommended_layout: string;

  /**
   * Two layout recommendations generated by AI.
   */
  layouts: LayoutOption[];
}