from enum import Enum

from pydantic import BaseModel, Field


# ---------------------------------------------------------
# Enums
# ---------------------------------------------------------

class LayoutType(str, Enum):
    """
    Supported layout types for MVP.
    """

    HERO = "hero"
    SPLIT = "split"
    MAGAZINE = "magazine"


class SectionType(str, Enum):
    """
    Supported page sections.
    """

    TITLE = "title"
    PARAGRAPH = "paragraph"
    IMAGE = "image"


# ---------------------------------------------------------
# Layout Section
# ---------------------------------------------------------

class LayoutSection(BaseModel):
    """
    Represents one content section of a layout.
    """

    type: SectionType

    text: str | None = None

    image_reference: int | None = Field(
        default=None,
        ge=0,
    )


# ---------------------------------------------------------
# Layout Option
# ---------------------------------------------------------

class LayoutOption(BaseModel):
    """
    One layout option generated by AI.
    """

    id: str

    layout_type: str

    layout_name: str

    description: str

    confidence: int = Field(
        ge=0,
        le=100,
    )

    sections: list[LayoutSection]


# ---------------------------------------------------------
# Response
# ---------------------------------------------------------

class GenerateLayoutResponse(BaseModel):
    """
    Response returned to Angular.
    """

    page_summary: str

    layout_options: list[LayoutOption]