from enum import Enum

from pydantic import BaseModel, Field


class ElementType(str, Enum):
    """
    Supported page element types.
    """

    TITLE = "title"
    PARAGRAPH = "paragraph"
    IMAGE = "image"


class Canvas(BaseModel):
    """
    Defines the logical page grid.
    """

    width: int = Field(default=12, ge=1)
    height: int = Field(default=12, ge=1)


class ElementPosition(BaseModel):
    """
    Grid position occupied by an element.
    """

    x: int = Field(ge=0)
    y: int = Field(ge=0)
    w: int = Field(gt=0)
    h: int = Field(gt=0)


class ElementStyle(BaseModel):
    """
    Rendering hints consumed by the frontend.
    """

    alignment: str | None = None
    font_size: str | None = None
    emphasis: str | None = None


class ElementContent(BaseModel):
    """
    Content rendered by the element.
    """

    text: str | None = None
    image_reference: int | None = None


class LayoutElement(BaseModel):
    """
    A single renderable element.
    """

    id: str

    type: ElementType

    content: ElementContent

    position: ElementPosition

    style: ElementStyle = Field(default_factory=ElementStyle)


class LayoutOption(BaseModel):
    """
    One layout generated by the AI.
    """

    id: str

    name: str

    description: str

    confidence: int = Field(ge=0, le=100)

    canvas: Canvas

    elements: list[LayoutElement]


class GenerateLayoutResponse(BaseModel):
    """
    Response returned to Angular.
    """

    page_summary: str

    layout_options: list[LayoutOption]